### PR TITLE
Depend on net-cookies-doc and net-cookies-lib seperately

### PR DESCRIPTION
**Pull request by LiberalArtist**

### CODE REVIEW

**Comment by jeapostrophe** [comment]
This must be applied at the same time as https://github.com/RenaissanceBug/racket-cookies/pull/6

**Comment by jeapostrophe** [comment]
Also, @LiberalArtist a test case broke: http://drdr.racket-lang.org/39268/racket/share/pkgs/web-server-test/tests/web-server/http/xexpr.rkt

**Comment by LiberalArtist** [comment]
Got it: `response/xexpr` was using the wrong `cookie?` in its contract.

**Comment by samth** [comment]
One other question: should net-cookies now be part of main-distribution?

**Comment by stamourv** [comment]
Since `net-cookies-lib` and `net-cookies-doc` will be by transitivity, I think that would make sense.
And `net-cookies-test` to `main-distribution-test`, too.

**Pull request merged**
