### PR TITLE
web-server/http/id-cookie: accept names & values as bytes; fix HMAC

### PR DESCRIPTION
**Pull request by LiberalArtist**
Not ready to merge.
Needs docs, tests, and a look at `typed/web-server/http`.

### CODE REVIEW

**Comment by LiberalArtist** [comment]
Related to https://github.com/racket/web-server/issues/74

**Comment by jeapostrophe** [comment]
Good work!

**Comment by LiberalArtist** [comment]
I should be able to finish this up in time for 7.5, but it may not be until the weekend, depending on how some other things go. (Branch day is Monday.)

**Comment by LiberalArtist** [comment]
Sorry this is so much later than I'd planned: I had some family obligations come up unexpectedly.

**Comment by LiberalArtist** [comment]
I'm still thinking through what to do for `typed/web-server/http`:
- I'm leaning toward not allowing `Bytes` for name and value arguments. In the untyped API, bytes are accepted for a mixture of consistency, backward-compatibility (per <https://github.com/RenaissanceBug/racket-cookies/commit/c745ee5>), and "be liberal in what you accept." In the typed world, none of the cookie-related functions have ever accepted `Bytes`: changing that seems likely to cause more problems than it would solve, particularly in that it would make argument and result types different.
- I'm conflicted about strengthening the type of the `#:timeout` argument for `valid-id-cookie?` and `request-id-cookie` to `Real` instead of `Number`. (A non-real `#:timeout` has always caused a runtime error: this PR just corrects that in the documentation and, in one case, the contract.) On the one hand, we made essentially the same change to `response-seconds` in <https://github.com/racket/typed-racket/commit/acf7707>, and that seemed to go fine. On the other hand, it would cause some buggy programs that previously compiled to fail to typecheck: personally, if I'm using static types, it's because I want buggy programs to be rejected at compile-time, but in a strict sense it would be a breaking change. It may or may not be relevant that, usually, you don't actually want to be using the `#:timeout` argument (see <https://github.com/racket/web-server/commit/626ad02>).

**Comment by jeapostrophe** [comment]
I don't have a strong opinion about the types. I follow your logic.

**Comment by LiberalArtist** [comment]
Subsumed by <https://github.com/racket/web-server/pull/84>

**Pull request closed without merging**
